### ISSUE TITLE
DisallowUnknownField crush when inline tag provided

### ISSUE THREAD

**Issue by itaischwartz** [goccy/go-yaml#121]
Hey @goccy,
I've added `disallowUnknownField` opt to TestDecoder_Inline.

```go
func TestDecoder_Inline(t *testing.T) {
	type Base struct {
		A int
		B string
	}
	yml := `---
a: 1
b: hello
c: true
`
	var v struct {
		*Base `yaml:",inline"`
		C     bool
	}
	if err := yaml.NewDecoder(strings.NewReader(yml), yaml.DisallowUnknownField()).Decode(&v); err != nil {
		t.Fatalf("%+v", err)
	}
	if v.A != 1 {
		t.Fatal("failed to decode with inline key")
	}
	if v.B != "hello" {
		t.Fatal("failed to decode with inline key")
	}
	if !v.C {
		t.Fatal("failed to decode with inline key")
	}
}
```  
The test yielded the following stack trace:
```
--- FAIL: TestDecoder_Inline (0.00s)
panic: reflect: NumField of non-struct type *yaml_test.Base [recovered]
        panic: reflect: NumField of non-struct type *yaml_test.Base

goroutine 27 [running]:
testing.tRunner.func1.1(0x11fb580, 0xc000332430)
        /usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc0003306c0)
        /usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:944 +0x3f9
panic(0x11fb580, 0xc000332430)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 +0x15d
reflect.(*rtype).NumField(0x11ef5c0, 0x1208240)
        /usr/local/Cellar/go/1.14/libexec/src/reflect/type.go:973 +0xb7
github.com/goccy/go-yaml.structFieldMap(0x12aff80, 0x11ef5c0, 0x196, 0x12aff80, 0x11ef5c0)
        /Users/user/work/go-yaml/struct.go:117 +0xcb
github.com/goccy/go-yaml.(*Decoder).deleteStructKeys(0xc0003034a0, 0x11ef5c0, 0xc000332280, 0x196, 0xc000334450, 0x121d060, 0xc00032c8a0)
        /Users/user/work/go-yaml/decode.go:366 +0x82
github.com/goccy/go-yaml.(*Decoder).decodeStruct(0xc0003034a0, 0x1218840, 0xc000332280, 0x199, 0x12adb00, 0xc000320d00, 0x28, 0x121cca0)
        /Users/user/work/go-yaml/decode.go:778 +0xde7
github.com/goccy/go-yaml.(*Decoder).decodeValue(0xc0003034a0, 0x1218840, 0xc000332280, 0x199, 0x12adb00, 0xc000320d00, 0x0, 0x1a)
        /Users/user/work/go-yaml/decode.go:471 +0x1b0a
github.com/goccy/go-yaml.(*Decoder).decode(0xc0003034a0, 0x11f4780, 0xc000332280, 0x16, 0x11f4780, 0x1414800)
        /Users/user/work/go-yaml/decode.go:1234 +0xd2
github.com/goccy/go-yaml.(*Decoder).Decode(0xc0003034a0, 0x11f4780, 0xc000332280, 0x10565f9, 0x730071671f62b)
        /Users/user/work/go-yaml/decode.go:1263 +0x272
github.com/goccy/go-yaml_test.TestDecoder_Inline(0xc0003306c0)
        /Users/user/work/go-yaml/decode_test.go:1314 +0x1da
testing.tRunner(0xc0003306c0, 0x125ebf0)
        /usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
        /usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1043 +0x357
FAIL    github.com/goccy/go-yaml        0.812s
FAIL
```

**Comment by goccy** [comment]
I fixed this issue with #123 and released as `v1.7.2` . Thanks !
