### ISSUE TITLE
Unmarshal literal with colon followed by non-space character should be strings

### ISSUE THREAD

**Issue by itchyny** [goccy/go-yaml#315]
Following code yields `map[string]interface {}{"v":map[string]interface {}{"a":0x0}}` but should yield `map[string]interface {}{"v":"a:0"}`.
```go
package main

import (
	"fmt"

	yaml "github.com/goccy/go-yaml"
)

func main() {
	var v interface{}
	err := yaml.Unmarshal([]byte(`v: a:0`), &v)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v\n", v)
}
```
Playground: https://go.dev/play/p/HtSrvqaV4B_o

Within the plain style string outside flow collection, `:` can be followed by [`ns-char`](https://yaml.org/spec/1.2.2/#rule-ns-char). So `a:0` should be interpreted as string. Likewise `a:~`, `a:!`, `a:#`, `a:$`, `a:^`, `a:<`, `a:-`, `a:%`, `a:*`, `a:<`, `a:[`, `a:{` should be strings.

Also, `a:]` and `a:}` should not cause panic.
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4d8ff7]

goroutine 1 [running]:
github.com/goccy/go-yaml/parser.(*parser).validateMapValue(0xc0000c00f0?, 0xc0000c00f0, {0x54d948?, 0xc0000c2040?}, {0x0, 0x0})
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/parser/parser.go:189 +0x57
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc00009aba0?, 0xc0000c00f0)
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/parser/parser.go:232 +0x225
github.com/goccy/go-yaml/parser.(*parser).createNodeFromToken(0x60eaa0?, 0xc0000a0510?, 0x0?)
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/parser/parser.go:575 +0x21e
github.com/goccy/go-yaml/parser.(*parser).parseToken(0x509320?, 0xc0000c00f0, 0x418266?)
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/parser/parser.go:560 +0x25
github.com/goccy/go-yaml/parser.(*parser).parse(0x0?, {0xc0000c2000?, 0x3?, 0x0?}, 0x0)
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/parser/parser.go:616 +0x16a
github.com/goccy/go-yaml/parser.Parse({0xc0000c2000?, 0xc0000ba000?, 0x3?}, 0x4f3d0a?)
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/parser/parser.go:652 +0x2f
github.com/goccy/go-yaml/parser.ParseBytes({0xc0000ba000?, 0x54c398?, 0xc0000a04e0?}, 0x7fe4105a05b8?)
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/parser/parser.go:642 +0x3d
github.com/goccy/go-yaml.(*Decoder).parse(0xc0000b8000, {0xc0000ba000?, 0x54c378?, 0xc0000a0450?})
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/decode.go:1474 +0x45
github.com/goccy/go-yaml.(*Decoder).decodeInit(0xc0000b8000)
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/decode.go:1502 +0xba
github.com/goccy/go-yaml.(*Decoder).DecodeContext(0xc0000b8000, {0x54c8a8, 0xc0000b2000}, {0x4fcac0?, 0xc00009e270?})
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/decode.go:1550 +0x1e6
github.com/goccy/go-yaml.UnmarshalContext({0x54c8a8, 0xc0000b2000}, {0xc0000b2010, 0x3, 0x3}, {0x4fcac0, 0xc00009e270}, {0x0, 0x0, 0x0})
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/yaml.go:191 +0x256
github.com/goccy/go-yaml.UnmarshalWithOptions(...)
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/yaml.go:185
github.com/goccy/go-yaml.Unmarshal(...)
	/tmp/gopath4273985801/pkg/mod/github.com/goccy/go-yaml@v1.9.5/yaml.go:179
main.main()
	/tmp/sandbox1165846406/prog.go:11 +0x7c

Program exited.
```

**Comment by goccy** [comment]
Thank you for your reporting ! This problem has already been resolved with latest release !
